# -*- coding: utf-8 -*-
"""always_getattribute.ipynb

Automatically generated by Colaboratory.

"""

class Book:
  def __init__(self, title, author, price):
    super().__init__()
    self.title = title
    self.author = author
    self.price = price
    self._discount = 0.1

  def __str__(self):
    return f"{self.title} by {self.author}, costs {self.price}"

  def __repr__(self):
    return f"title={self.title} author={self.author} costs={self.price}"

# Ilekroc atrybut bedzie wywolywany ponizsza funkcja bedzie wywolywana super() zeby wyjsc do class Book i uniknac petli
  def __getattribute__(self, name):
    if name == "price":
      p = super().__getattribute__("price")
      d = super().__getattribute__("_discount")
      return p - (p * d)
    return super().__getattribute__(name)
    

# Nie wyswietli 49.99 tylko 44.991
b1 = Book("war and peace", "lew tolstoj", 49.99)
print(b1)
