# -*- coding: utf-8 -*-
"""inhert2.ipynb

Automatically generated by Colaboratory.
"""

class Publication:
  def __init__(self, title, price):
    self.title = title
    self.price = price


class Periodical(Publication):
  def __init__(self, title, publisher, price, period):
    super().__init__(title, price)
    self.publisher = publisher
    self.period = period

class Book(Publication):
  def __init__(self, title, author, pages, price):
    super().__init__(title, price)
    self.author = author
    self.pages = pages


  
class Magazine(Periodical):
  def __init__(self, title, publisher, price, period):
    super().__init__(title, publisher, price, period)


class Newspaper(Periodical):
  def __init__(self, title, publisher, price, period):
    super().__init__(title, publisher, price, period)


b1 = Book("Woja i pokoj", "lew", 665, 35.99)
m1 = Magazine("TV Time", "Super Company", 4.99, "monthly")
n1 = Newspaper("Polityka", "Kombinat", 5.99, "weekly")
print(b1.title)
print(m1.title)
print(n1.publisher)
