# -*- coding: utf-8 -*-
"""poo_v2_multiple_inheritance.ipynb

Automatically generated by Colaboratory.
"""

#multiple inheritance in python


class A:
  def __init__(self):
    super().__init__()
    self.foo = "foo"
    self.name = "Class A"


class B:
  def __init__(self):
    super().__init__()
    self.bar = "bar"
    self.name = "Class B"


class C(A, B):
  def __init__(self):
    super().__init__()

  def showprops(self):
    print(self.foo)
    print(self.bar)
    print(self.name)


c = C()
c.showprops()
print(C.__mro__)
