# -*- coding: utf-8 -*-
"""Python_Object4.ipynb

Automatically generated by Colaboratory.

"""

class Book:
  BOOK_TYPES = ("HARDCOVER", "PAPERBACK", "EBOOK")


  __booklist =  None    # __ ukryty przed innymi klasami 

  @classmethod
  def getbooktypes(cls): #class object not instance not an object instance
    return cls.BOOK_TYPES

  @staticmethod
  def getbooklist():
    if Book.__booklist == None:
      Book.__booklist = []
    return Book.__booklist

  def setTitle(self, newtitle):
    self.title = newtitle

  def __init__(self, title, booktype):
    self.title = title
    if (not booktype in Book.BOOK_TYPES):
      raise ValueError(f"{booktype} is not a valid book type")
    else:
      self.booktype = booktype




print("Book types: ", Book.getbooktypes()) # nie trzeba inicjowac klasy

b1 = Book("Title 1", "EBOOK")

thebooks = Book.getbooklist()
print(thebooks)
thebooks.append(b1)
thebooks.append(b2)
print(thebooks)
