# -*- coding: utf-8 -*-
"""Python_Object1.ipynb

Automatically generated by Colaboratory.

"""

class Book:
  def __init__(self, title):
    self.title = title

b1 = Book('Problem 3 cial')
b2 = Book('wspomnienie o przeszlosci')

print(b1)
print(b1.title)
